/*
 * Gamepad Desktop Control
 * Copyright (c) 2015. Ievgen Starodiedov
 */

package com.ghosty.desktop.gamepad.ui;

import com.ghosty.desktop.gamepad.prop.PropertyManager;

import javax.swing.JCheckBox;
import java.awt.Toolkit;

/**
 * @author Ghosty
 */
public class Settings extends javax.swing.JFrame {

    public static final String LEFT_CLICK_PROPERTY_NAME = "gdc.left.click";
    public static final String RIGHT_CLICK_PROPERTY_NAME = "gdc.right.click";
    private final PropertyManager propertyManager = PropertyManager.getInstance();

    private static Settings instance;

    public static synchronized Settings getInstance() {
        if (instance == null) {
            instance = new Settings();
        }
        return instance;
    }

    /**
     * Creates new form Settings
     */
    private Settings() {
        initComponents();
        lmbTextBox.setText(propertyManager.getProperty(LEFT_CLICK_PROPERTY_NAME));
        rmbTextBox.setText(propertyManager.getProperty(RIGHT_CLICK_PROPERTY_NAME));
        lmbTextBox.addMouseListener(new TextBoxesOneMouseClickListener(lmbTextBox, LEFT_CLICK_PROPERTY_NAME));
        rmbTextBox.addMouseListener(new TextBoxesOneMouseClickListener(rmbTextBox, RIGHT_CLICK_PROPERTY_NAME));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lmbLabel = new javax.swing.JLabel();
        rmbLabel = new javax.swing.JLabel();
        buttonsHeader = new javax.swing.JLabel();
        lmbTextBox = new javax.swing.JTextField();
        rmbTextBox = new javax.swing.JTextField();
        autoStartupCheckBox = new javax.swing.JCheckBox();

        setTitle("Settings");
        setIconImage(Toolkit.getDefaultToolkit().getImage("img/TrayIcon.PNG"));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(220, 160));
        setMinimumSize(new java.awt.Dimension(220, 160));
        setPreferredSize(new java.awt.Dimension(220, 160));
        setResizable(false);

        lmbLabel.setText("Left Mouse Click");
        lmbLabel.setToolTipText("");

        rmbLabel.setText("Right Mouse Click");

        buttonsHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonsHeader.setText("Buttons");

        lmbTextBox.setEditable(false);
        lmbTextBox.setText("jTextField1");

        rmbTextBox.setEditable(false);
        rmbTextBox.setText("jTextField2");

        autoStartupCheckBox.setText("Start when system starts");
        autoStartupCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoStartupCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(buttonsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lmbLabel)
                                                        .addComponent(rmbLabel))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rmbTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                                        .addComponent(lmbTextBox))))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(autoStartupCheckBox)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonsHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lmbLabel)
                                        .addComponent(lmbTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rmbLabel)
                                        .addComponent(rmbTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(autoStartupCheckBox)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autoStartupCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoStartupCheckBoxActionPerformed
        propertyManager.setProperty("gdc.auto.startup", String.valueOf(((JCheckBox) evt.getSource()).isSelected()));
        propertyManager.storeProperties();
    }//GEN-LAST:event_autoStartupCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoStartupCheckBox;
    private javax.swing.JLabel buttonsHeader;
    private javax.swing.JLabel lmbLabel;
    private javax.swing.JTextField lmbTextBox;
    private javax.swing.JLabel rmbLabel;
    private javax.swing.JTextField rmbTextBox;
    // End of variables declaration//GEN-END:variables
}
